// Code generated by go generate; DO NOT EDIT.
package html

import "github.com/go-live-view/go-live-view/rend"

// Elements

func Html(children ...rend.Node) *ElementNode {
	return Element("html", children...)
}

func Base(children ...rend.Node) *VoidNode {
	return Void("base", children...)
}

func Head(children ...rend.Node) *ElementNode {
	return Element("head", children...)
}

func Link(children ...rend.Node) *VoidNode {
	return Void("link", children...)
}

func Meta(children ...rend.Node) *VoidNode {
	return Void("meta", children...)
}

func Style(children ...rend.Node) *ElementNode {
	return Element("style", children...)
}

func Title(children ...rend.Node) *ElementNode {
	return Element("title", children...)
}

func Body(children ...rend.Node) *ElementNode {
	return Element("body", children...)
}

func Address(children ...rend.Node) *ElementNode {
	return Element("address", children...)
}

func Article(children ...rend.Node) *ElementNode {
	return Element("article", children...)
}

func Aside(children ...rend.Node) *ElementNode {
	return Element("aside", children...)
}

func Footer(children ...rend.Node) *ElementNode {
	return Element("footer", children...)
}

func Header(children ...rend.Node) *ElementNode {
	return Element("header", children...)
}

func H1(children ...rend.Node) *ElementNode {
	return Element("h1", children...)
}

func H2(children ...rend.Node) *ElementNode {
	return Element("h2", children...)
}

func H3(children ...rend.Node) *ElementNode {
	return Element("h3", children...)
}

func H4(children ...rend.Node) *ElementNode {
	return Element("h4", children...)
}

func H5(children ...rend.Node) *ElementNode {
	return Element("h5", children...)
}

func H6(children ...rend.Node) *ElementNode {
	return Element("h6", children...)
}

func Hgroup(children ...rend.Node) *ElementNode {
	return Element("hgroup", children...)
}

func Main(children ...rend.Node) *ElementNode {
	return Element("main", children...)
}

func Nav(children ...rend.Node) *ElementNode {
	return Element("nav", children...)
}

func Section(children ...rend.Node) *ElementNode {
	return Element("section", children...)
}

func Search(children ...rend.Node) *ElementNode {
	return Element("search", children...)
}

func Blockquote(children ...rend.Node) *ElementNode {
	return Element("blockquote", children...)
}

func Dd(children ...rend.Node) *ElementNode {
	return Element("dd", children...)
}

func Div(children ...rend.Node) *ElementNode {
	return Element("div", children...)
}

func Dl(children ...rend.Node) *ElementNode {
	return Element("dl", children...)
}

func Dt(children ...rend.Node) *ElementNode {
	return Element("dt", children...)
}

func Figcaption(children ...rend.Node) *ElementNode {
	return Element("figcaption", children...)
}

func Figure(children ...rend.Node) *ElementNode {
	return Element("figure", children...)
}

func Hr(children ...rend.Node) *VoidNode {
	return Void("hr", children...)
}

func Li(children ...rend.Node) *ElementNode {
	return Element("li", children...)
}

func Menu(children ...rend.Node) *ElementNode {
	return Element("menu", children...)
}

func Ol(children ...rend.Node) *ElementNode {
	return Element("ol", children...)
}

func P(children ...rend.Node) *ElementNode {
	return Element("p", children...)
}

func Pre(children ...rend.Node) *ElementNode {
	return Element("pre", children...)
}

func Ul(children ...rend.Node) *ElementNode {
	return Element("ul", children...)
}

func A(children ...rend.Node) *ElementNode {
	return Element("a", children...)
}

func Abbr(children ...rend.Node) *ElementNode {
	return Element("abbr", children...)
}

func B(children ...rend.Node) *ElementNode {
	return Element("b", children...)
}

func Bdi(children ...rend.Node) *ElementNode {
	return Element("bdi", children...)
}

func Bdo(children ...rend.Node) *ElementNode {
	return Element("bdo", children...)
}

func Br(children ...rend.Node) *VoidNode {
	return Void("br", children...)
}

func Cite(children ...rend.Node) *ElementNode {
	return Element("cite", children...)
}

func Code(children ...rend.Node) *ElementNode {
	return Element("code", children...)
}

func Data(children ...rend.Node) *ElementNode {
	return Element("data", children...)
}

func Dfn(children ...rend.Node) *ElementNode {
	return Element("dfn", children...)
}

func Em(children ...rend.Node) *ElementNode {
	return Element("em", children...)
}

func I(children ...rend.Node) *ElementNode {
	return Element("i", children...)
}

func Kbd(children ...rend.Node) *ElementNode {
	return Element("kbd", children...)
}

func Mark(children ...rend.Node) *ElementNode {
	return Element("mark", children...)
}

func Q(children ...rend.Node) *ElementNode {
	return Element("q", children...)
}

func Rp(children ...rend.Node) *ElementNode {
	return Element("rp", children...)
}

func Rt(children ...rend.Node) *ElementNode {
	return Element("rt", children...)
}

func Ruby(children ...rend.Node) *ElementNode {
	return Element("ruby", children...)
}

func S(children ...rend.Node) *ElementNode {
	return Element("s", children...)
}

func Samp(children ...rend.Node) *ElementNode {
	return Element("samp", children...)
}

func Small(children ...rend.Node) *ElementNode {
	return Element("small", children...)
}

func Span(children ...rend.Node) *ElementNode {
	return Element("span", children...)
}

func Strong(children ...rend.Node) *ElementNode {
	return Element("strong", children...)
}

func Sub(children ...rend.Node) *ElementNode {
	return Element("sub", children...)
}

func Sup(children ...rend.Node) *ElementNode {
	return Element("sup", children...)
}

func Time(children ...rend.Node) *ElementNode {
	return Element("time", children...)
}

func U(children ...rend.Node) *ElementNode {
	return Element("u", children...)
}

func Var(children ...rend.Node) *ElementNode {
	return Element("var", children...)
}

func Wbr(children ...rend.Node) *ElementNode {
	return Element("wbr", children...)
}

func Area(children ...rend.Node) *VoidNode {
	return Void("area", children...)
}

func Audio(children ...rend.Node) *ElementNode {
	return Element("audio", children...)
}

func Img(children ...rend.Node) *VoidNode {
	return Void("img", children...)
}

func Map(children ...rend.Node) *ElementNode {
	return Element("map", children...)
}

func Track(children ...rend.Node) *VoidNode {
	return Void("track", children...)
}

func Video(children ...rend.Node) *ElementNode {
	return Element("video", children...)
}

func Embed(children ...rend.Node) *VoidNode {
	return Void("embed", children...)
}

func Fencedframe(children ...rend.Node) *ElementNode {
	return Element("fencedframe", children...)
}

func Iframe(children ...rend.Node) *ElementNode {
	return Element("iframe", children...)
}

func Object(children ...rend.Node) *ElementNode {
	return Element("object", children...)
}

func Picture(children ...rend.Node) *ElementNode {
	return Element("picture", children...)
}

func Source(children ...rend.Node) *VoidNode {
	return Void("source", children...)
}

func Svg(children ...rend.Node) *ElementNode {
	return Element("svg", children...)
}

func Math(children ...rend.Node) *ElementNode {
	return Element("math", children...)
}

func Canvas(children ...rend.Node) *ElementNode {
	return Element("canvas", children...)
}

func Noscript(children ...rend.Node) *ElementNode {
	return Element("noscript", children...)
}

func Script(children ...rend.Node) *ElementNode {
	return Element("script", children...)
}

func Del(children ...rend.Node) *ElementNode {
	return Element("del", children...)
}

func Ins(children ...rend.Node) *ElementNode {
	return Element("ins", children...)
}

func Caption(children ...rend.Node) *ElementNode {
	return Element("caption", children...)
}

func Col(children ...rend.Node) *VoidNode {
	return Void("col", children...)
}

func Colgroup(children ...rend.Node) *ElementNode {
	return Element("colgroup", children...)
}

func Table(children ...rend.Node) *ElementNode {
	return Element("table", children...)
}

func Tbody(children ...rend.Node) *ElementNode {
	return Element("tbody", children...)
}

func Td(children ...rend.Node) *ElementNode {
	return Element("td", children...)
}

func Tfoot(children ...rend.Node) *ElementNode {
	return Element("tfoot", children...)
}

func Th(children ...rend.Node) *ElementNode {
	return Element("th", children...)
}

func Thead(children ...rend.Node) *ElementNode {
	return Element("thead", children...)
}

func Tr(children ...rend.Node) *ElementNode {
	return Element("tr", children...)
}

func Button(children ...rend.Node) *ElementNode {
	return Element("button", children...)
}

func Datalist(children ...rend.Node) *ElementNode {
	return Element("datalist", children...)
}

func Fieldset(children ...rend.Node) *ElementNode {
	return Element("fieldset", children...)
}

func Form(children ...rend.Node) *ElementNode {
	return Element("form", children...)
}

func Input(children ...rend.Node) *VoidNode {
	return Void("input", children...)
}

func Label(children ...rend.Node) *ElementNode {
	return Element("label", children...)
}

func Legend(children ...rend.Node) *ElementNode {
	return Element("legend", children...)
}

func Meter(children ...rend.Node) *ElementNode {
	return Element("meter", children...)
}

func Optgroup(children ...rend.Node) *ElementNode {
	return Element("optgroup", children...)
}

func Option(children ...rend.Node) *ElementNode {
	return Element("option", children...)
}

func Output(children ...rend.Node) *ElementNode {
	return Element("output", children...)
}

func Progress(children ...rend.Node) *ElementNode {
	return Element("progress", children...)
}

func Select(children ...rend.Node) *ElementNode {
	return Element("select", children...)
}

func Selectedcontent(children ...rend.Node) *ElementNode {
	return Element("selectedcontent", children...)
}

func Textarea(children ...rend.Node) *ElementNode {
	return Element("textarea", children...)
}

func Details(children ...rend.Node) *ElementNode {
	return Element("details", children...)
}

func Dialog(children ...rend.Node) *ElementNode {
	return Element("dialog", children...)
}

func Summary(children ...rend.Node) *ElementNode {
	return Element("summary", children...)
}

func Slot(children ...rend.Node) *ElementNode {
	return Element("slot", children...)
}

func Template(children ...rend.Node) *ElementNode {
	return Element("template", children...)
}

func Acronym(children ...rend.Node) *ElementNode {
	return Element("acronym", children...)
}

func Big(children ...rend.Node) *ElementNode {
	return Element("big", children...)
}

func Center(children ...rend.Node) *ElementNode {
	return Element("center", children...)
}

func Font(children ...rend.Node) *ElementNode {
	return Element("font", children...)
}

func Frame(children ...rend.Node) *ElementNode {
	return Element("frame", children...)
}

func Frameset(children ...rend.Node) *ElementNode {
	return Element("frameset", children...)
}

func Marquee(children ...rend.Node) *ElementNode {
	return Element("marquee", children...)
}

func Nobr(children ...rend.Node) *ElementNode {
	return Element("nobr", children...)
}

func Noframes(children ...rend.Node) *ElementNode {
	return Element("noframes", children...)
}

func Param(children ...rend.Node) *VoidNode {
	return Void("param", children...)
}

func Plaintext(children ...rend.Node) *VoidNode {
	return Void("plaintext", children...)
}

func Rb(children ...rend.Node) *VoidNode {
	return Void("rb", children...)
}

func Rtc(children ...rend.Node) *ElementNode {
	return Element("rtc", children...)
}

func Strike(children ...rend.Node) *ElementNode {
	return Element("strike", children...)
}

func Tt(children ...rend.Node) *ElementNode {
	return Element("tt", children...)
}

func Xmp(children ...rend.Node) *ElementNode {
	return Element("xmp", children...)
}

// Attributes

func AAttr(value ...string) *AttributeNode {
	return Attr("A", value...)
}

func AttributeAttr(value ...string) *AttributeNode {
	return Attr("Attribute", value...)
}

func Canvasrenderingcontext2dAttr(value ...string) *AttributeNode {
	return Attr("CanvasRenderingContext2D", value...)
}

func ElementAttr(value ...string) *AttributeNode {
	return Attr("Element", value...)
}

func GetAttr(value ...string) *AttributeNode {
	return Attr("GET", value...)
}

func HtmlaudioelementAttr(value ...string) *AttributeNode {
	return Attr("HTMLAudioElement", value...)
}

func HtmlbodyelementAttr(value ...string) *AttributeNode {
	return Attr("HTMLBodyElement", value...)
}

func HtmldialogelementAttr(value ...string) *AttributeNode {
	return Attr("HTMLDialogElement", value...)
}

func HtmlimageelementAttr(value ...string) *AttributeNode {
	return Attr("HTMLImageElement", value...)
}

func HtmlmarqueeelementAttr(value ...string) *AttributeNode {
	return Attr("HTMLMarqueeElement", value...)
}

func HtmlmediaelementAttr(value ...string) *AttributeNode {
	return Attr("HTMLMediaElement", value...)
}

func IAttr(value ...string) *AttributeNode {
	return Attr("I", value...)
}

func LinkAttr(value ...string) *AttributeNode {
	return Attr("Link", value...)
}

func PostAttr(value ...string) *AttributeNode {
	return Attr("POST", value...)
}

func RefererAttr(value ...string) *AttributeNode {
	return Attr("Referer", value...)
}

func ShadowrootAttr(value ...string) *AttributeNode {
	return Attr("ShadowRoot", value...)
}

func AbbrAttr(value ...string) *AttributeNode {
	return Attr("abbr", value...)
}

func AcceptAttr(value ...string) *AttributeNode {
	return Attr("accept", value...)
}

func AccesskeyAttr(value ...string) *AttributeNode {
	return Attr("accesskey", value...)
}

func AccumulateAttr(value ...string) *AttributeNode {
	return Attr("accumulate", value...)
}

func AcronymAttr(value ...string) *AttributeNode {
	return Attr("acronym", value...)
}

func ActionAttr(value ...string) *AttributeNode {
	return Attr("action", value...)
}

func AdditiveAttr(value ...string) *AttributeNode {
	return Attr("additive", value...)
}

func AddressAttr(value ...string) *AttributeNode {
	return Attr("address", value...)
}

func AlignAttr(value ...string) *AttributeNode {
	return Attr("align", value...)
}

func AlinkAttr(value ...string) *AttributeNode {
	return Attr("alink", value...)
}

func AllowAttr(value ...string) *AttributeNode {
	return Attr("allow", value...)
}

func AllowfullscreenAttr(value ...string) *AttributeNode {
	return Attr("allowfullscreen", value...)
}

func AllowpaymentrequestAttr(value ...string) *AttributeNode {
	return Attr("allowpaymentrequest", value...)
}

func AltAttr(value ...string) *AttributeNode {
	return Attr("alt", value...)
}

func AmpAttr(value ...string) *AttributeNode {
	return Attr("amp", value...)
}

func AmplitudeAttr(value ...string) *AttributeNode {
	return Attr("amplitude", value...)
}

func AnchorAttr(value ...string) *AttributeNode {
	return Attr("anchor", value...)
}

func AnimateAttr(value ...string) *AttributeNode {
	return Attr("animate", value...)
}

func AnimatemotionAttr(value ...string) *AttributeNode {
	return Attr("animateMotion", value...)
}

func AnimatetransformAttr(value ...string) *AttributeNode {
	return Attr("animateTransform", value...)
}

func AnnotationAttr(value ...string) *AttributeNode {
	return Attr("annotation", value...)
}

func AnonymousAttr(value ...string) *AttributeNode {
	return Attr("anonymous", value...)
}

func AnyAttr(value ...string) *AttributeNode {
	return Attr("any", value...)
}

func AposAttr(value ...string) *AttributeNode {
	return Attr("apos", value...)
}

func ArchiveAttr(value ...string) *AttributeNode {
	return Attr("archive", value...)
}

func AreaAttr(value ...string) *AttributeNode {
	return Attr("area", value...)
}

func AriaAttr(value ...string) *AttributeNode {
	return Attr("aria-*", value...)
}

func ArticleAttr(value ...string) *AttributeNode {
	return Attr("article", value...)
}

func AsAttr(value ...string) *AttributeNode {
	return Attr("as", value...)
}

func AsideAttr(value ...string) *AttributeNode {
	return Attr("aside", value...)
}

func AsyncAttr(value ...string) *AttributeNode {
	return Attr("async", value...)
}

func AttributenameAttr(value ...string) *AttributeNode {
	return Attr("attributeName", value...)
}

func AttributetypeAttr(value ...string) *AttributeNode {
	return Attr("attributeType", value...)
}

func AttributionsrcAttr(value ...string) *AttributeNode {
	return Attr("attributionSrc", value...)
}

func AudioAttr(value ...string) *AttributeNode {
	return Attr("audio", value...)
}

func AudioprocessAttr(value ...string) *AttributeNode {
	return Attr("audioprocess", value...)
}

func AutoAttr(value ...string) *AttributeNode {
	return Attr("auto", value...)
}

func AutocapitalizeAttr(value ...string) *AttributeNode {
	return Attr("autocapitalize", value...)
}

func AutocompleteAttr(value ...string) *AttributeNode {
	return Attr("autocomplete", value...)
}

func AutocorrectAttr(value ...string) *AttributeNode {
	return Attr("autocorrect", value...)
}

func AutofocusAttr(value ...string) *AttributeNode {
	return Attr("autofocus", value...)
}

func AutoplayAttr(value ...string) *AttributeNode {
	return Attr("autoplay", value...)
}

func AxisAttr(value ...string) *AttributeNode {
	return Attr("axis", value...)
}

func AzimuthAttr(value ...string) *AttributeNode {
	return Attr("azimuth", value...)
}

func BAttr(value ...string) *AttributeNode {
	return Attr("b", value...)
}

func BackdropAttr(value ...string) *AttributeNode {
	return Attr("backdrop", value...)
}

func BackgroundAttr(value ...string) *AttributeNode {
	return Attr("background", value...)
}

func BaseAttr(value ...string) *AttributeNode {
	return Attr("base", value...)
}

func BasefrequencyAttr(value ...string) *AttributeNode {
	return Attr("baseFrequency", value...)
}

func BaseprofileAttr(value ...string) *AttributeNode {
	return Attr("baseProfile", value...)
}

func BdiAttr(value ...string) *AttributeNode {
	return Attr("bdi", value...)
}

func BdoAttr(value ...string) *AttributeNode {
	return Attr("bdo", value...)
}

func BeginAttr(value ...string) *AttributeNode {
	return Attr("begin", value...)
}

func BehaviorAttr(value ...string) *AttributeNode {
	return Attr("behavior", value...)
}

func BgcolorAttr(value ...string) *AttributeNode {
	return Attr("bgcolor", value...)
}

func BiasAttr(value ...string) *AttributeNode {
	return Attr("bias", value...)
}

func BigAttr(value ...string) *AttributeNode {
	return Attr("big", value...)
}

func BlankAttr(value ...string) *AttributeNode {
	return Attr("blank", value...)
}

func BlobAttr(value ...string) *AttributeNode {
	return Attr("blob", value...)
}

func BlockAttr(value ...string) *AttributeNode {
	return Attr("block", value...)
}

func BlockingAttr(value ...string) *AttributeNode {
	return Attr("blocking", value...)
}

func BlockquoteAttr(value ...string) *AttributeNode {
	return Attr("blockquote", value...)
}

func BodyAttr(value ...string) *AttributeNode {
	return Attr("body", value...)
}

func BoldAttr(value ...string) *AttributeNode {
	return Attr("bold", value...)
}

func BorderAttr(value ...string) *AttributeNode {
	return Attr("border", value...)
}

func BottomAttr(value ...string) *AttributeNode {
	return Attr("bottom", value...)
}

func BottommarginAttr(value ...string) *AttributeNode {
	return Attr("bottommargin", value...)
}

func BrAttr(value ...string) *AttributeNode {
	return Attr("br", value...)
}

func BrowsingtopicsAttr(value ...string) *AttributeNode {
	return Attr("browsingtopics", value...)
}

func ButtonAttr(value ...string) *AttributeNode {
	return Attr("button", value...)
}

func ByAttr(value ...string) *AttributeNode {
	return Attr("by", value...)
}

func CalcmodeAttr(value ...string) *AttributeNode {
	return Attr("calcMode", value...)
}

func CancelAttr(value ...string) *AttributeNode {
	return Attr("cancel", value...)
}

func CanplayAttr(value ...string) *AttributeNode {
	return Attr("canplay", value...)
}

func CanplaythroughAttr(value ...string) *AttributeNode {
	return Attr("canplaythrough", value...)
}

func CanvasAttr(value ...string) *AttributeNode {
	return Attr("canvas", value...)
}

func CaptionAttr(value ...string) *AttributeNode {
	return Attr("caption", value...)
}

func CaptionsAttr(value ...string) *AttributeNode {
	return Attr("captions", value...)
}

func CaptureAttr(value ...string) *AttributeNode {
	return Attr("capture", value...)
}

func CellpaddingAttr(value ...string) *AttributeNode {
	return Attr("cellpadding", value...)
}

func CellspacingAttr(value ...string) *AttributeNode {
	return Attr("cellspacing", value...)
}

func CenterAttr(value ...string) *AttributeNode {
	return Attr("center", value...)
}

func ChangeAttr(value ...string) *AttributeNode {
	return Attr("change", value...)
}

func ChaptersAttr(value ...string) *AttributeNode {
	return Attr("chapters", value...)
}

func CharAttr(value ...string) *AttributeNode {
	return Attr("char", value...)
}

func CharoffAttr(value ...string) *AttributeNode {
	return Attr("charoff", value...)
}

func CharsetAttr(value ...string) *AttributeNode {
	return Attr("charset", value...)
}

func CheckvalidityAttr(value ...string) *AttributeNode {
	return Attr("checkValidity", value...)
}

func CheckboxAttr(value ...string) *AttributeNode {
	return Attr("checkbox", value...)
}

func CheckedAttr(value ...string) *AttributeNode {
	return Attr("checked", value...)
}

func CircleAttr(value ...string) *AttributeNode {
	return Attr("circle", value...)
}

func CiteAttr(value ...string) *AttributeNode {
	return Attr("cite", value...)
}

func ClassAttr(value ...string) *AttributeNode {
	return Attr("class", value...)
}

func ClassidAttr(value ...string) *AttributeNode {
	return Attr("classid", value...)
}

func ClearAttr(value ...string) *AttributeNode {
	return Attr("clear", value...)
}

func ClickAttr(value ...string) *AttributeNode {
	return Attr("click", value...)
}

func ClipAttr(value ...string) *AttributeNode {
	return Attr("clip", value...)
}

func ClippathAttr(value ...string) *AttributeNode {
	return Attr("clipPath", value...)
}

func ClippathunitsAttr(value ...string) *AttributeNode {
	return Attr("clipPathUnits", value...)
}

func CloseAttr(value ...string) *AttributeNode {
	return Attr("close", value...)
}

func ClosedAttr(value ...string) *AttributeNode {
	return Attr("closed", value...)
}

func ClosedbyAttr(value ...string) *AttributeNode {
	return Attr("closedby", value...)
}

func CloserequestAttr(value ...string) *AttributeNode {
	return Attr("closerequest", value...)
}

func CodeAttr(value ...string) *AttributeNode {
	return Attr("code", value...)
}

func CodebaseAttr(value ...string) *AttributeNode {
	return Attr("codebase", value...)
}

func CodetypeAttr(value ...string) *AttributeNode {
	return Attr("codetype", value...)
}

func ColAttr(value ...string) *AttributeNode {
	return Attr("col", value...)
}

func ColgroupAttr(value ...string) *AttributeNode {
	return Attr("colgroup", value...)
}

func CollapseAttr(value ...string) *AttributeNode {
	return Attr("collapse", value...)
}

func ColorAttr(value ...string) *AttributeNode {
	return Attr("color", value...)
}

func ColsAttr(value ...string) *AttributeNode {
	return Attr("cols", value...)
}

func ColspanAttr(value ...string) *AttributeNode {
	return Attr("colspan", value...)
}

func ComboboxAttr(value ...string) *AttributeNode {
	return Attr("combobox", value...)
}

func CommandAttr(value ...string) *AttributeNode {
	return Attr("command", value...)
}

func CommandforAttr(value ...string) *AttributeNode {
	return Attr("commandfor", value...)
}

func CompactAttr(value ...string) *AttributeNode {
	return Attr("compact", value...)
}

func CompleteAttr(value ...string) *AttributeNode {
	return Attr("complete", value...)
}

func ContentAttr(value ...string) *AttributeNode {
	return Attr("content", value...)
}

func ContenteditableAttr(value ...string) *AttributeNode {
	return Attr("contenteditable", value...)
}

func ControlsAttr(value ...string) *AttributeNode {
	return Attr("controls", value...)
}

func ControlslistAttr(value ...string) *AttributeNode {
	return Attr("controlslist", value...)
}

func CoordsAttr(value ...string) *AttributeNode {
	return Attr("coords", value...)
}

func CredentiallessAttr(value ...string) *AttributeNode {
	return Attr("credentialless", value...)
}

func CrossoriginAttr(value ...string) *AttributeNode {
	return Attr("crossorigin", value...)
}

func CspAttr(value ...string) *AttributeNode {
	return Attr("csp", value...)
}

func CursorAttr(value ...string) *AttributeNode {
	return Attr("cursor", value...)
}

func CxAttr(value ...string) *AttributeNode {
	return Attr("cx", value...)
}

func CyAttr(value ...string) *AttributeNode {
	return Attr("cy", value...)
}

func DAttr(value ...string) *AttributeNode {
	return Attr("d", value...)
}

func DatalistAttr(value ...string) *AttributeNode {
	return Attr("datalist", value...)
}

func DateAttr(value ...string) *AttributeNode {
	return Attr("date", value...)
}

func DatetimeAttr(value ...string) *AttributeNode {
	return Attr("datetime", value...)
}

func DdAttr(value ...string) *AttributeNode {
	return Attr("dd", value...)
}

func DeclareAttr(value ...string) *AttributeNode {
	return Attr("declare", value...)
}

func DecodingAttr(value ...string) *AttributeNode {
	return Attr("decoding", value...)
}

func DefaultAttr(value ...string) *AttributeNode {
	return Attr("default", value...)
}

func DefaultvalueAttr(value ...string) *AttributeNode {
	return Attr("defaultValue", value...)
}

func DeferAttr(value ...string) *AttributeNode {
	return Attr("defer", value...)
}

func DefsAttr(value ...string) *AttributeNode {
	return Attr("defs", value...)
}

func DelAttr(value ...string) *AttributeNode {
	return Attr("del", value...)
}

func DescAttr(value ...string) *AttributeNode {
	return Attr("desc", value...)
}

func DetailsAttr(value ...string) *AttributeNode {
	return Attr("details", value...)
}

func DfnAttr(value ...string) *AttributeNode {
	return Attr("dfn", value...)
}

func DialogAttr(value ...string) *AttributeNode {
	return Attr("dialog", value...)
}

func DiffuseconstantAttr(value ...string) *AttributeNode {
	return Attr("diffuseConstant", value...)
}

func DirAttr(value ...string) *AttributeNode {
	return Attr("dir", value...)
}

func DirectionAttr(value ...string) *AttributeNode {
	return Attr("direction", value...)
}

func DirnameAttr(value ...string) *AttributeNode {
	return Attr("dirname", value...)
}

func DisabledAttr(value ...string) *AttributeNode {
	return Attr("disabled", value...)
}

func DisablepictureinpictureAttr(value ...string) *AttributeNode {
	return Attr("disablepictureinpicture", value...)
}

func DisableremoteplaybackAttr(value ...string) *AttributeNode {
	return Attr("disableremoteplayback", value...)
}

func DiscAttr(value ...string) *AttributeNode {
	return Attr("disc", value...)
}

func DisplayAttr(value ...string) *AttributeNode {
	return Attr("display", value...)
}

func DisplaystyleAttr(value ...string) *AttributeNode {
	return Attr("displaystyle", value...)
}

func DivAttr(value ...string) *AttributeNode {
	return Attr("div", value...)
}

func DivisorAttr(value ...string) *AttributeNode {
	return Attr("divisor", value...)
}

func DlAttr(value ...string) *AttributeNode {
	return Attr("dl", value...)
}

func DocumentAttr(value ...string) *AttributeNode {
	return Attr("document", value...)
}

func DownloadAttr(value ...string) *AttributeNode {
	return Attr("download", value...)
}

func DraggableAttr(value ...string) *AttributeNode {
	return Attr("draggable", value...)
}

func DtAttr(value ...string) *AttributeNode {
	return Attr("dt", value...)
}

func DurAttr(value ...string) *AttributeNode {
	return Attr("dur", value...)
}

func DurationchangeAttr(value ...string) *AttributeNode {
	return Attr("durationchange", value...)
}

func DxAttr(value ...string) *AttributeNode {
	return Attr("dx", value...)
}

func DyAttr(value ...string) *AttributeNode {
	return Attr("dy", value...)
}

func EagerAttr(value ...string) *AttributeNode {
	return Attr("eager", value...)
}

func EdgemodeAttr(value ...string) *AttributeNode {
	return Attr("edgeMode", value...)
}

func ElementtimingAttr(value ...string) *AttributeNode {
	return Attr("elementtiming", value...)
}

func ElevationAttr(value ...string) *AttributeNode {
	return Attr("elevation", value...)
}

func EllipseAttr(value ...string) *AttributeNode {
	return Attr("ellipse", value...)
}

func EmAttr(value ...string) *AttributeNode {
	return Attr("em", value...)
}

func EmailAttr(value ...string) *AttributeNode {
	return Attr("email", value...)
}

func EmbedAttr(value ...string) *AttributeNode {
	return Attr("embed", value...)
}

func EmptiedAttr(value ...string) *AttributeNode {
	return Attr("emptied", value...)
}

func EnabledAttr(value ...string) *AttributeNode {
	return Attr("enabled", value...)
}

func EnctypeAttr(value ...string) *AttributeNode {
	return Attr("enctype", value...)
}

func EndAttr(value ...string) *AttributeNode {
	return Attr("end", value...)
}

func EndedAttr(value ...string) *AttributeNode {
	return Attr("ended", value...)
}

func EnterkeyhintAttr(value ...string) *AttributeNode {
	return Attr("enterkeyhint", value...)
}

func ErrorAttr(value ...string) *AttributeNode {
	return Attr("error", value...)
}

func ExponentAttr(value ...string) *AttributeNode {
	return Attr("exponent", value...)
}

func ExportpartsAttr(value ...string) *AttributeNode {
	return Attr("exportparts", value...)
}

func FaceAttr(value ...string) *AttributeNode {
	return Attr("face", value...)
}

func FalseAttr(value ...string) *AttributeNode {
	return Attr("false", value...)
}

func FeblendAttr(value ...string) *AttributeNode {
	return Attr("feBlend", value...)
}

func FecolormatrixAttr(value ...string) *AttributeNode {
	return Attr("feColorMatrix", value...)
}

func FecomponenttransferAttr(value ...string) *AttributeNode {
	return Attr("feComponentTransfer", value...)
}

func FecompositeAttr(value ...string) *AttributeNode {
	return Attr("feComposite", value...)
}

func FeconvolvematrixAttr(value ...string) *AttributeNode {
	return Attr("feConvolveMatrix", value...)
}

func FediffuselightingAttr(value ...string) *AttributeNode {
	return Attr("feDiffuseLighting", value...)
}

func FedisplacementmapAttr(value ...string) *AttributeNode {
	return Attr("feDisplacementMap", value...)
}

func FedistantlightAttr(value ...string) *AttributeNode {
	return Attr("feDistantLight", value...)
}

func FedropshadowAttr(value ...string) *AttributeNode {
	return Attr("feDropShadow", value...)
}

func FefloodAttr(value ...string) *AttributeNode {
	return Attr("feFlood", value...)
}

func FefuncaAttr(value ...string) *AttributeNode {
	return Attr("feFuncA", value...)
}

func FefuncbAttr(value ...string) *AttributeNode {
	return Attr("feFuncB", value...)
}

func FefuncgAttr(value ...string) *AttributeNode {
	return Attr("feFuncG", value...)
}

func FefuncrAttr(value ...string) *AttributeNode {
	return Attr("feFuncR", value...)
}

func FegaussianblurAttr(value ...string) *AttributeNode {
	return Attr("feGaussianBlur", value...)
}

func FeimageAttr(value ...string) *AttributeNode {
	return Attr("feImage", value...)
}

func FemergeAttr(value ...string) *AttributeNode {
	return Attr("feMerge", value...)
}

func FemergenodeAttr(value ...string) *AttributeNode {
	return Attr("feMergeNode", value...)
}

func FemorphologyAttr(value ...string) *AttributeNode {
	return Attr("feMorphology", value...)
}

func FeoffsetAttr(value ...string) *AttributeNode {
	return Attr("feOffset", value...)
}

func FepointlightAttr(value ...string) *AttributeNode {
	return Attr("fePointLight", value...)
}

func FespecularlightingAttr(value ...string) *AttributeNode {
	return Attr("feSpecularLighting", value...)
}

func FespotlightAttr(value ...string) *AttributeNode {
	return Attr("feSpotLight", value...)
}

func FetileAttr(value ...string) *AttributeNode {
	return Attr("feTile", value...)
}

func FeturbulenceAttr(value ...string) *AttributeNode {
	return Attr("feTurbulence", value...)
}

func FencedframeAttr(value ...string) *AttributeNode {
	return Attr("fencedframe", value...)
}

func FetchAttr(value ...string) *AttributeNode {
	return Attr("fetch", value...)
}

func FetchpriorityAttr(value ...string) *AttributeNode {
	return Attr("fetchpriority", value...)
}

func FieldsetAttr(value ...string) *AttributeNode {
	return Attr("fieldset", value...)
}

func FigcaptionAttr(value ...string) *AttributeNode {
	return Attr("figcaption", value...)
}

func FigureAttr(value ...string) *AttributeNode {
	return Attr("figure", value...)
}

func FileAttr(value ...string) *AttributeNode {
	return Attr("file", value...)
}

func FilenameAttr(value ...string) *AttributeNode {
	return Attr("filename", value...)
}

func FillAttr(value ...string) *AttributeNode {
	return Attr("fill", value...)
}

func FilterAttr(value ...string) *AttributeNode {
	return Attr("filter", value...)
}

func FilterunitsAttr(value ...string) *AttributeNode {
	return Attr("filterUnits", value...)
}

func FontAttr(value ...string) *AttributeNode {
	return Attr("font", value...)
}

func FooterAttr(value ...string) *AttributeNode {
	return Attr("footer", value...)
}

func ForAttr(value ...string) *AttributeNode {
	return Attr("for", value...)
}

func ForeignobjectAttr(value ...string) *AttributeNode {
	return Attr("foreignObject", value...)
}

func FormAttr(value ...string) *AttributeNode {
	return Attr("form", value...)
}

func FormactionAttr(value ...string) *AttributeNode {
	return Attr("formaction", value...)
}

func FormenctypeAttr(value ...string) *AttributeNode {
	return Attr("formenctype", value...)
}

func FormmethodAttr(value ...string) *AttributeNode {
	return Attr("formmethod", value...)
}

func FormnovalidateAttr(value ...string) *AttributeNode {
	return Attr("formnovalidate", value...)
}

func FormtargetAttr(value ...string) *AttributeNode {
	return Attr("formtarget", value...)
}

func FrAttr(value ...string) *AttributeNode {
	return Attr("fr", value...)
}

func FrameAttr(value ...string) *AttributeNode {
	return Attr("frame", value...)
}

func FrameborderAttr(value ...string) *AttributeNode {
	return Attr("frameborder", value...)
}

func FramesetAttr(value ...string) *AttributeNode {
	return Attr("frameset", value...)
}

func FromAttr(value ...string) *AttributeNode {
	return Attr("from", value...)
}

func FxAttr(value ...string) *AttributeNode {
	return Attr("fx", value...)
}

func FyAttr(value ...string) *AttributeNode {
	return Attr("fy", value...)
}

func GAttr(value ...string) *AttributeNode {
	return Attr("g", value...)
}

func GradienttransformAttr(value ...string) *AttributeNode {
	return Attr("gradientTransform", value...)
}

func GradientunitsAttr(value ...string) *AttributeNode {
	return Attr("gradientUnits", value...)
}

func H1Attr(value ...string) *AttributeNode {
	return Attr("h1", value...)
}

func H2Attr(value ...string) *AttributeNode {
	return Attr("h2", value...)
}

func H3Attr(value ...string) *AttributeNode {
	return Attr("h3", value...)
}

func H4Attr(value ...string) *AttributeNode {
	return Attr("h4", value...)
}

func H6Attr(value ...string) *AttributeNode {
	return Attr("h6", value...)
}

func HardAttr(value ...string) *AttributeNode {
	return Attr("hard", value...)
}

func HeadAttr(value ...string) *AttributeNode {
	return Attr("head", value...)
}

func HeaderAttr(value ...string) *AttributeNode {
	return Attr("header", value...)
}

func HeadersAttr(value ...string) *AttributeNode {
	return Attr("headers", value...)
}

func HeightAttr(value ...string) *AttributeNode {
	return Attr("height", value...)
}

func HgroupAttr(value ...string) *AttributeNode {
	return Attr("hgroup", value...)
}

func HiddenAttr(value ...string) *AttributeNode {
	return Attr("hidden", value...)
}

func HideAttr(value ...string) *AttributeNode {
	return Attr("hide", value...)
}

func HighAttr(value ...string) *AttributeNode {
	return Attr("high", value...)
}

func HostAttr(value ...string) *AttributeNode {
	return Attr("host", value...)
}

func HrAttr(value ...string) *AttributeNode {
	return Attr("hr", value...)
}

func HrefAttr(value ...string) *AttributeNode {
	return Attr("href", value...)
}

func HreflangAttr(value ...string) *AttributeNode {
	return Attr("hreflang", value...)
}

func HspaceAttr(value ...string) *AttributeNode {
	return Attr("hspace", value...)
}

func HtmlAttr(value ...string) *AttributeNode {
	return Attr("html", value...)
}

func HyphensAttr(value ...string) *AttributeNode {
	return Attr("hyphens", value...)
}

func IdAttr(value ...string) *AttributeNode {
	return Attr("id", value...)
}

func IfAttr(value ...string) *AttributeNode {
	return Attr("if", value...)
}

func IframeAttr(value ...string) *AttributeNode {
	return Attr("iframe", value...)
}

func ImageAttr(value ...string) *AttributeNode {
	return Attr("image", value...)
}

func ImagesizesAttr(value ...string) *AttributeNode {
	return Attr("imagesizes", value...)
}

func ImagesrcsetAttr(value ...string) *AttributeNode {
	return Attr("imagesrcset", value...)
}

func ImgAttr(value ...string) *AttributeNode {
	return Attr("img", value...)
}

func ImportmapAttr(value ...string) *AttributeNode {
	return Attr("importmap", value...)
}

func InAttr(value ...string) *AttributeNode {
	return Attr("in", value...)
}

func In2Attr(value ...string) *AttributeNode {
	return Attr("in2", value...)
}

func IncrementalAttr(value ...string) *AttributeNode {
	return Attr("incremental", value...)
}

func IndeterminateAttr(value ...string) *AttributeNode {
	return Attr("indeterminate", value...)
}

func InertAttr(value ...string) *AttributeNode {
	return Attr("inert", value...)
}

func InlineAttr(value ...string) *AttributeNode {
	return Attr("inline", value...)
}

func InputAttr(value ...string) *AttributeNode {
	return Attr("input", value...)
}

func InputmodeAttr(value ...string) *AttributeNode {
	return Attr("inputmode", value...)
}

func InsAttr(value ...string) *AttributeNode {
	return Attr("ins", value...)
}

func IntegrityAttr(value ...string) *AttributeNode {
	return Attr("integrity", value...)
}

func InterceptAttr(value ...string) *AttributeNode {
	return Attr("intercept", value...)
}

func InvalidAttr(value ...string) *AttributeNode {
	return Attr("invalid", value...)
}

func IsAttr(value ...string) *AttributeNode {
	return Attr("is", value...)
}

func IsindexAttr(value ...string) *AttributeNode {
	return Attr("isindex", value...)
}

func IsmapAttr(value ...string) *AttributeNode {
	return Attr("ismap", value...)
}

func ItemidAttr(value ...string) *AttributeNode {
	return Attr("itemid", value...)
}

func ItempropAttr(value ...string) *AttributeNode {
	return Attr("itemprop", value...)
}

func ItemrefAttr(value ...string) *AttributeNode {
	return Attr("itemref", value...)
}

func ItemscopeAttr(value ...string) *AttributeNode {
	return Attr("itemscope", value...)
}

func ItemtypeAttr(value ...string) *AttributeNode {
	return Attr("itemtype", value...)
}

func JavascriptAttr(value ...string) *AttributeNode {
	return Attr("javascript", value...)
}

func K1Attr(value ...string) *AttributeNode {
	return Attr("k1", value...)
}

func K2Attr(value ...string) *AttributeNode {
	return Attr("k2", value...)
}

func K3Attr(value ...string) *AttributeNode {
	return Attr("k3", value...)
}

func K4Attr(value ...string) *AttributeNode {
	return Attr("k4", value...)
}

func KbdAttr(value ...string) *AttributeNode {
	return Attr("kbd", value...)
}

func KernelmatrixAttr(value ...string) *AttributeNode {
	return Attr("kernelMatrix", value...)
}

func KernelunitlengthAttr(value ...string) *AttributeNode {
	return Attr("kernelUnitLength", value...)
}

func KeypointsAttr(value ...string) *AttributeNode {
	return Attr("keyPoints", value...)
}

func KeysplinesAttr(value ...string) *AttributeNode {
	return Attr("keySplines", value...)
}

func KeytimesAttr(value ...string) *AttributeNode {
	return Attr("keyTimes", value...)
}

func KindAttr(value ...string) *AttributeNode {
	return Attr("kind", value...)
}

func LabelAttr(value ...string) *AttributeNode {
	return Attr("label", value...)
}

func LangAttr(value ...string) *AttributeNode {
	return Attr("lang", value...)
}

func LanguageAttr(value ...string) *AttributeNode {
	return Attr("language", value...)
}

func LazyAttr(value ...string) *AttributeNode {
	return Attr("lazy", value...)
}

func LeftAttr(value ...string) *AttributeNode {
	return Attr("left", value...)
}

func LeftmarginAttr(value ...string) *AttributeNode {
	return Attr("leftmargin", value...)
}

func LegendAttr(value ...string) *AttributeNode {
	return Attr("legend", value...)
}

func LengthadjustAttr(value ...string) *AttributeNode {
	return Attr("lengthAdjust", value...)
}

func LiAttr(value ...string) *AttributeNode {
	return Attr("li", value...)
}

func LimitingconeangleAttr(value ...string) *AttributeNode {
	return Attr("limitingConeAngle", value...)
}

func LineAttr(value ...string) *AttributeNode {
	return Attr("line", value...)
}

func LineargradientAttr(value ...string) *AttributeNode {
	return Attr("linearGradient", value...)
}

func ListAttr(value ...string) *AttributeNode {
	return Attr("list", value...)
}

func LoadAttr(value ...string) *AttributeNode {
	return Attr("load", value...)
}

func LoadeddataAttr(value ...string) *AttributeNode {
	return Attr("loadeddata", value...)
}

func LoadedmetadataAttr(value ...string) *AttributeNode {
	return Attr("loadedmetadata", value...)
}

func LoadingAttr(value ...string) *AttributeNode {
	return Attr("loading", value...)
}

func LoadstartAttr(value ...string) *AttributeNode {
	return Attr("loadstart", value...)
}

func LongdescAttr(value ...string) *AttributeNode {
	return Attr("longdesc", value...)
}

func LoopAttr(value ...string) *AttributeNode {
	return Attr("loop", value...)
}

func LowAttr(value ...string) *AttributeNode {
	return Attr("low", value...)
}

func LtAttr(value ...string) *AttributeNode {
	return Attr("lt", value...)
}

func LtrAttr(value ...string) *AttributeNode {
	return Attr("ltr", value...)
}

func MactionAttr(value ...string) *AttributeNode {
	return Attr("maction", value...)
}

func MailtoAttr(value ...string) *AttributeNode {
	return Attr("mailto", value...)
}

func MainAttr(value ...string) *AttributeNode {
	return Attr("main", value...)
}

func ManualAttr(value ...string) *AttributeNode {
	return Attr("manual", value...)
}

func MapAttr(value ...string) *AttributeNode {
	return Attr("map", value...)
}

func MarginAttr(value ...string) *AttributeNode {
	return Attr("margin", value...)
}

func MarginheightAttr(value ...string) *AttributeNode {
	return Attr("marginheight", value...)
}

func MarginwidthAttr(value ...string) *AttributeNode {
	return Attr("marginwidth", value...)
}

func MarkAttr(value ...string) *AttributeNode {
	return Attr("mark", value...)
}

func MarkerAttr(value ...string) *AttributeNode {
	return Attr("marker", value...)
}

func MarkerheightAttr(value ...string) *AttributeNode {
	return Attr("markerHeight", value...)
}

func MarkerunitsAttr(value ...string) *AttributeNode {
	return Attr("markerUnits", value...)
}

func MarkerwidthAttr(value ...string) *AttributeNode {
	return Attr("markerWidth", value...)
}

func MarqueeAttr(value ...string) *AttributeNode {
	return Attr("marquee", value...)
}

func MaskAttr(value ...string) *AttributeNode {
	return Attr("mask", value...)
}

func MaskcontentunitsAttr(value ...string) *AttributeNode {
	return Attr("maskContentUnits", value...)
}

func MaskunitsAttr(value ...string) *AttributeNode {
	return Attr("maskUnits", value...)
}

func MathAttr(value ...string) *AttributeNode {
	return Attr("math", value...)
}

func MathbackgroundAttr(value ...string) *AttributeNode {
	return Attr("mathbackground", value...)
}

func MathcolorAttr(value ...string) *AttributeNode {
	return Attr("mathcolor", value...)
}

func MathsizeAttr(value ...string) *AttributeNode {
	return Attr("mathsize", value...)
}

func MaxAttr(value ...string) *AttributeNode {
	return Attr("max", value...)
}

func MaxlengthAttr(value ...string) *AttributeNode {
	return Attr("maxlength", value...)
}

func MediaAttr(value ...string) *AttributeNode {
	return Attr("media", value...)
}

func MencloseAttr(value ...string) *AttributeNode {
	return Attr("menclose", value...)
}

func MenuAttr(value ...string) *AttributeNode {
	return Attr("menu", value...)
}

func MenuitemAttr(value ...string) *AttributeNode {
	return Attr("menuitem", value...)
}

func MenuitemcheckboxAttr(value ...string) *AttributeNode {
	return Attr("menuitemcheckbox", value...)
}

func MenuitemradioAttr(value ...string) *AttributeNode {
	return Attr("menuitemradio", value...)
}

func MerrorAttr(value ...string) *AttributeNode {
	return Attr("merror", value...)
}

func MetaAttr(value ...string) *AttributeNode {
	return Attr("meta", value...)
}

func MetadataAttr(value ...string) *AttributeNode {
	return Attr("metadata", value...)
}

func MeterAttr(value ...string) *AttributeNode {
	return Attr("meter", value...)
}

func MethodAttr(value ...string) *AttributeNode {
	return Attr("method", value...)
}

func MfencedAttr(value ...string) *AttributeNode {
	return Attr("mfenced", value...)
}

func MfracAttr(value ...string) *AttributeNode {
	return Attr("mfrac", value...)
}

func MiAttr(value ...string) *AttributeNode {
	return Attr("mi", value...)
}

func MiddleAttr(value ...string) *AttributeNode {
	return Attr("middle", value...)
}

func MinAttr(value ...string) *AttributeNode {
	return Attr("min", value...)
}

func MinlengthAttr(value ...string) *AttributeNode {
	return Attr("minlength", value...)
}

func MmultiscriptsAttr(value ...string) *AttributeNode {
	return Attr("mmultiscripts", value...)
}

func MnAttr(value ...string) *AttributeNode {
	return Attr("mn", value...)
}

func MoAttr(value ...string) *AttributeNode {
	return Attr("mo", value...)
}

func ModeAttr(value ...string) *AttributeNode {
	return Attr("mode", value...)
}

func ModuleAttr(value ...string) *AttributeNode {
	return Attr("module", value...)
}

func MonospaceAttr(value ...string) *AttributeNode {
	return Attr("monospace", value...)
}

func MonthAttr(value ...string) *AttributeNode {
	return Attr("month", value...)
}

func MoverAttr(value ...string) *AttributeNode {
	return Attr("mover", value...)
}

func MpaddedAttr(value ...string) *AttributeNode {
	return Attr("mpadded", value...)
}

func MpathAttr(value ...string) *AttributeNode {
	return Attr("mpath", value...)
}

func MphantomAttr(value ...string) *AttributeNode {
	return Attr("mphantom", value...)
}

func MprescriptsAttr(value ...string) *AttributeNode {
	return Attr("mprescripts", value...)
}

func MrootAttr(value ...string) *AttributeNode {
	return Attr("mroot", value...)
}

func MrowAttr(value ...string) *AttributeNode {
	return Attr("mrow", value...)
}

func MsAttr(value ...string) *AttributeNode {
	return Attr("ms", value...)
}

func MspaceAttr(value ...string) *AttributeNode {
	return Attr("mspace", value...)
}

func MsqrtAttr(value ...string) *AttributeNode {
	return Attr("msqrt", value...)
}

func MstyleAttr(value ...string) *AttributeNode {
	return Attr("mstyle", value...)
}

func MsubAttr(value ...string) *AttributeNode {
	return Attr("msub", value...)
}

func MsubsupAttr(value ...string) *AttributeNode {
	return Attr("msubsup", value...)
}

func MsupAttr(value ...string) *AttributeNode {
	return Attr("msup", value...)
}

func MtableAttr(value ...string) *AttributeNode {
	return Attr("mtable", value...)
}

func MtdAttr(value ...string) *AttributeNode {
	return Attr("mtd", value...)
}

func MtextAttr(value ...string) *AttributeNode {
	return Attr("mtext", value...)
}

func MtrAttr(value ...string) *AttributeNode {
	return Attr("mtr", value...)
}

func MultipleAttr(value ...string) *AttributeNode {
	return Attr("multiple", value...)
}

func MunderAttr(value ...string) *AttributeNode {
	return Attr("munder", value...)
}

func MunderoverAttr(value ...string) *AttributeNode {
	return Attr("munderover", value...)
}

func MutedAttr(value ...string) *AttributeNode {
	return Attr("muted", value...)
}

func NameAttr(value ...string) *AttributeNode {
	return Attr("name", value...)
}

func NavAttr(value ...string) *AttributeNode {
	return Attr("nav", value...)
}

func NextAttr(value ...string) *AttributeNode {
	return Attr("next", value...)
}

func NoAttr(value ...string) *AttributeNode {
	return Attr("no", value...)
}

func NobrAttr(value ...string) *AttributeNode {
	return Attr("nobr", value...)
}

func NoembedAttr(value ...string) *AttributeNode {
	return Attr("noembed", value...)
}

func NoframesAttr(value ...string) *AttributeNode {
	return Attr("noframes", value...)
}

func NomoduleAttr(value ...string) *AttributeNode {
	return Attr("nomodule", value...)
}

func NonceAttr(value ...string) *AttributeNode {
	return Attr("nonce", value...)
}

func NoneAttr(value ...string) *AttributeNode {
	return Attr("none", value...)
}

func NoresizeAttr(value ...string) *AttributeNode {
	return Attr("noresize", value...)
}

func NormalAttr(value ...string) *AttributeNode {
	return Attr("normal", value...)
}

func NoscriptAttr(value ...string) *AttributeNode {
	return Attr("noscript", value...)
}

func NoshadeAttr(value ...string) *AttributeNode {
	return Attr("noshade", value...)
}

func NotanaudioAttr(value ...string) *AttributeNode {
	return Attr("notanaudio", value...)
}

func NotavideoAttr(value ...string) *AttributeNode {
	return Attr("notavideo", value...)
}

func NovalidateAttr(value ...string) *AttributeNode {
	return Attr("novalidate", value...)
}

func NullAttr(value ...string) *AttributeNode {
	return Attr("null", value...)
}

func NumoctavesAttr(value ...string) *AttributeNode {
	return Attr("numOctaves", value...)
}

func NumberAttr(value ...string) *AttributeNode {
	return Attr("number", value...)
}

func ObjectAttr(value ...string) *AttributeNode {
	return Attr("object", value...)
}

func OffAttr(value ...string) *AttributeNode {
	return Attr("off", value...)
}

func OlAttr(value ...string) *AttributeNode {
	return Attr("ol", value...)
}

func OnAttr(value ...string) *AttributeNode {
	return Attr("on", value...)
}

func OnabortAttr(value ...string) *AttributeNode {
	return Attr("onabort", value...)
}

func OnafterprintAttr(value ...string) *AttributeNode {
	return Attr("onafterprint", value...)
}

func OnautocompleteAttr(value ...string) *AttributeNode {
	return Attr("onautocomplete", value...)
}

func OnautocompleteerrorAttr(value ...string) *AttributeNode {
	return Attr("onautocompleteerror", value...)
}

func OnbeforeprintAttr(value ...string) *AttributeNode {
	return Attr("onbeforeprint", value...)
}

func OnbeforeunloadAttr(value ...string) *AttributeNode {
	return Attr("onbeforeunload", value...)
}

func OnblurAttr(value ...string) *AttributeNode {
	return Attr("onblur", value...)
}

func OncancelAttr(value ...string) *AttributeNode {
	return Attr("oncancel", value...)
}

func OncanplayAttr(value ...string) *AttributeNode {
	return Attr("oncanplay", value...)
}

func OncanplaythroughAttr(value ...string) *AttributeNode {
	return Attr("oncanplaythrough", value...)
}

func OnchangeAttr(value ...string) *AttributeNode {
	return Attr("onchange", value...)
}

func OnclickAttr(value ...string) *AttributeNode {
	return Attr("onclick", value...)
}

func OncloseAttr(value ...string) *AttributeNode {
	return Attr("onclose", value...)
}

func OncontextmenuAttr(value ...string) *AttributeNode {
	return Attr("oncontextmenu", value...)
}

func OncuechangeAttr(value ...string) *AttributeNode {
	return Attr("oncuechange", value...)
}

func OndblclickAttr(value ...string) *AttributeNode {
	return Attr("ondblclick", value...)
}

func OndragAttr(value ...string) *AttributeNode {
	return Attr("ondrag", value...)
}

func OndragendAttr(value ...string) *AttributeNode {
	return Attr("ondragend", value...)
}

func OndragenterAttr(value ...string) *AttributeNode {
	return Attr("ondragenter", value...)
}

func OndragleaveAttr(value ...string) *AttributeNode {
	return Attr("ondragleave", value...)
}

func OndragoverAttr(value ...string) *AttributeNode {
	return Attr("ondragover", value...)
}

func OndragstartAttr(value ...string) *AttributeNode {
	return Attr("ondragstart", value...)
}

func OndropAttr(value ...string) *AttributeNode {
	return Attr("ondrop", value...)
}

func OndurationchangeAttr(value ...string) *AttributeNode {
	return Attr("ondurationchange", value...)
}

func OnemptiedAttr(value ...string) *AttributeNode {
	return Attr("onemptied", value...)
}

func OnendedAttr(value ...string) *AttributeNode {
	return Attr("onended", value...)
}

func OnerrorAttr(value ...string) *AttributeNode {
	return Attr("onerror", value...)
}

func OnfocusAttr(value ...string) *AttributeNode {
	return Attr("onfocus", value...)
}

func OnhashchangeAttr(value ...string) *AttributeNode {
	return Attr("onhashchange", value...)
}

func OninputAttr(value ...string) *AttributeNode {
	return Attr("oninput", value...)
}

func OninvalidAttr(value ...string) *AttributeNode {
	return Attr("oninvalid", value...)
}

func OnkeydownAttr(value ...string) *AttributeNode {
	return Attr("onkeydown", value...)
}

func OnkeypressAttr(value ...string) *AttributeNode {
	return Attr("onkeypress", value...)
}

func OnkeyupAttr(value ...string) *AttributeNode {
	return Attr("onkeyup", value...)
}

func OnlanguagechangeAttr(value ...string) *AttributeNode {
	return Attr("onlanguagechange", value...)
}

func OnloadAttr(value ...string) *AttributeNode {
	return Attr("onload", value...)
}

func OnloadeddataAttr(value ...string) *AttributeNode {
	return Attr("onloadeddata", value...)
}

func OnloadedmetadataAttr(value ...string) *AttributeNode {
	return Attr("onloadedmetadata", value...)
}

func OnloadstartAttr(value ...string) *AttributeNode {
	return Attr("onloadstart", value...)
}

func OnmessageAttr(value ...string) *AttributeNode {
	return Attr("onmessage", value...)
}

func OnmessageerrorAttr(value ...string) *AttributeNode {
	return Attr("onmessageerror", value...)
}

func OnmousedownAttr(value ...string) *AttributeNode {
	return Attr("onmousedown", value...)
}

func OnmouseenterAttr(value ...string) *AttributeNode {
	return Attr("onmouseenter", value...)
}

func OnmouseleaveAttr(value ...string) *AttributeNode {
	return Attr("onmouseleave", value...)
}

func OnmousemoveAttr(value ...string) *AttributeNode {
	return Attr("onmousemove", value...)
}

func OnmouseoutAttr(value ...string) *AttributeNode {
	return Attr("onmouseout", value...)
}

func OnmouseoverAttr(value ...string) *AttributeNode {
	return Attr("onmouseover", value...)
}

func OnmouseupAttr(value ...string) *AttributeNode {
	return Attr("onmouseup", value...)
}

func OnmousewheelAttr(value ...string) *AttributeNode {
	return Attr("onmousewheel", value...)
}

func OnofflineAttr(value ...string) *AttributeNode {
	return Attr("onoffline", value...)
}

func OnonlineAttr(value ...string) *AttributeNode {
	return Attr("ononline", value...)
}

func OnpagehideAttr(value ...string) *AttributeNode {
	return Attr("onpagehide", value...)
}

func OnpagerevealAttr(value ...string) *AttributeNode {
	return Attr("onpagereveal", value...)
}

func OnpageshowAttr(value ...string) *AttributeNode {
	return Attr("onpageshow", value...)
}

func OnpageswapAttr(value ...string) *AttributeNode {
	return Attr("onpageswap", value...)
}

func OnpauseAttr(value ...string) *AttributeNode {
	return Attr("onpause", value...)
}

func OnplayAttr(value ...string) *AttributeNode {
	return Attr("onplay", value...)
}

func OnplayingAttr(value ...string) *AttributeNode {
	return Attr("onplaying", value...)
}

func OnpopstateAttr(value ...string) *AttributeNode {
	return Attr("onpopstate", value...)
}

func OnprogressAttr(value ...string) *AttributeNode {
	return Attr("onprogress", value...)
}

func OnratechangeAttr(value ...string) *AttributeNode {
	return Attr("onratechange", value...)
}

func OnrejectionhandledAttr(value ...string) *AttributeNode {
	return Attr("onrejectionhandled", value...)
}

func OnresetAttr(value ...string) *AttributeNode {
	return Attr("onreset", value...)
}

func OnresizeAttr(value ...string) *AttributeNode {
	return Attr("onresize", value...)
}

func OnscrollAttr(value ...string) *AttributeNode {
	return Attr("onscroll", value...)
}

func OnseekedAttr(value ...string) *AttributeNode {
	return Attr("onseeked", value...)
}

func OnseekingAttr(value ...string) *AttributeNode {
	return Attr("onseeking", value...)
}

func OnselectAttr(value ...string) *AttributeNode {
	return Attr("onselect", value...)
}

func OnshowAttr(value ...string) *AttributeNode {
	return Attr("onshow", value...)
}

func OnsortAttr(value ...string) *AttributeNode {
	return Attr("onsort", value...)
}

func OnstalledAttr(value ...string) *AttributeNode {
	return Attr("onstalled", value...)
}

func OnstorageAttr(value ...string) *AttributeNode {
	return Attr("onstorage", value...)
}

func OnsubmitAttr(value ...string) *AttributeNode {
	return Attr("onsubmit", value...)
}

func OnsuspendAttr(value ...string) *AttributeNode {
	return Attr("onsuspend", value...)
}

func OntimeupdateAttr(value ...string) *AttributeNode {
	return Attr("ontimeupdate", value...)
}

func OntoggleAttr(value ...string) *AttributeNode {
	return Attr("ontoggle", value...)
}

func OnunhandledrejectionAttr(value ...string) *AttributeNode {
	return Attr("onunhandledrejection", value...)
}

func OnunloadAttr(value ...string) *AttributeNode {
	return Attr("onunload", value...)
}

func OnvolumechangeAttr(value ...string) *AttributeNode {
	return Attr("onvolumechange", value...)
}

func OnwaitingAttr(value ...string) *AttributeNode {
	return Attr("onwaiting", value...)
}

func OpacityAttr(value ...string) *AttributeNode {
	return Attr("opacity", value...)
}

func OpenAttr(value ...string) *AttributeNode {
	return Attr("open", value...)
}

func OperatorAttr(value ...string) *AttributeNode {
	return Attr("operator", value...)
}

func OptgroupAttr(value ...string) *AttributeNode {
	return Attr("optgroup", value...)
}

func OptimumAttr(value ...string) *AttributeNode {
	return Attr("optimum", value...)
}

func OptionAttr(value ...string) *AttributeNode {
	return Attr("option", value...)
}

func OptionalAttr(value ...string) *AttributeNode {
	return Attr("optional", value...)
}

func OrderAttr(value ...string) *AttributeNode {
	return Attr("order", value...)
}

func OrientAttr(value ...string) *AttributeNode {
	return Attr("orient", value...)
}

func OriginAttr(value ...string) *AttributeNode {
	return Attr("origin", value...)
}

func OutputAttr(value ...string) *AttributeNode {
	return Attr("output", value...)
}

func OverflowAttr(value ...string) *AttributeNode {
	return Attr("overflow", value...)
}

func OverlayAttr(value ...string) *AttributeNode {
	return Attr("overlay", value...)
}

func PAttr(value ...string) *AttributeNode {
	return Attr("p", value...)
}

func PaddingAttr(value ...string) *AttributeNode {
	return Attr("padding", value...)
}

func ParamAttr(value ...string) *AttributeNode {
	return Attr("param", value...)
}

func ParentAttr(value ...string) *AttributeNode {
	return Attr("parent", value...)
}

func PartAttr(value ...string) *AttributeNode {
	return Attr("part", value...)
}

func PasswordAttr(value ...string) *AttributeNode {
	return Attr("password", value...)
}

func PathAttr(value ...string) *AttributeNode {
	return Attr("path", value...)
}

func PathlengthAttr(value ...string) *AttributeNode {
	return Attr("pathLength", value...)
}

func PatternAttr(value ...string) *AttributeNode {
	return Attr("pattern", value...)
}

func PatterncontentunitsAttr(value ...string) *AttributeNode {
	return Attr("patternContentUnits", value...)
}

func PatterntransformAttr(value ...string) *AttributeNode {
	return Attr("patternTransform", value...)
}

func PatternunitsAttr(value ...string) *AttributeNode {
	return Attr("patternUnits", value...)
}

func PauseAttr(value ...string) *AttributeNode {
	return Attr("pause", value...)
}

func PictureAttr(value ...string) *AttributeNode {
	return Attr("picture", value...)
}

func PingAttr(value ...string) *AttributeNode {
	return Attr("ping", value...)
}

func PlaceholderAttr(value ...string) *AttributeNode {
	return Attr("placeholder", value...)
}

func PlaintextAttr(value ...string) *AttributeNode {
	return Attr("plaintext", value...)
}

func PlayAttr(value ...string) *AttributeNode {
	return Attr("play", value...)
}

func PlayingAttr(value ...string) *AttributeNode {
	return Attr("playing", value...)
}

func PlaysinlineAttr(value ...string) *AttributeNode {
	return Attr("playsinline", value...)
}

func PointsAttr(value ...string) *AttributeNode {
	return Attr("points", value...)
}

func PointsatxAttr(value ...string) *AttributeNode {
	return Attr("pointsAtX", value...)
}

func PointsatyAttr(value ...string) *AttributeNode {
	return Attr("pointsAtY", value...)
}

func PointsatzAttr(value ...string) *AttributeNode {
	return Attr("pointsAtZ", value...)
}

func PolyAttr(value ...string) *AttributeNode {
	return Attr("poly", value...)
}

func PolygonAttr(value ...string) *AttributeNode {
	return Attr("polygon", value...)
}

func PolylineAttr(value ...string) *AttributeNode {
	return Attr("polyline", value...)
}

func PopoverAttr(value ...string) *AttributeNode {
	return Attr("popover", value...)
}

func PopovertargetAttr(value ...string) *AttributeNode {
	return Attr("popovertarget", value...)
}

func PopovertargetactionAttr(value ...string) *AttributeNode {
	return Attr("popovertargetaction", value...)
}

func PosterAttr(value ...string) *AttributeNode {
	return Attr("poster", value...)
}

func PreAttr(value ...string) *AttributeNode {
	return Attr("pre", value...)
}

func PreloadAttr(value ...string) *AttributeNode {
	return Attr("preload", value...)
}

func PresentationAttr(value ...string) *AttributeNode {
	return Attr("presentation", value...)
}

func PreservealphaAttr(value ...string) *AttributeNode {
	return Attr("preserveAlpha", value...)
}

func PreserveaspectratioAttr(value ...string) *AttributeNode {
	return Attr("preserveAspectRatio", value...)
}

func PrimitiveunitsAttr(value ...string) *AttributeNode {
	return Attr("primitiveUnits", value...)
}

func ProfileAttr(value ...string) *AttributeNode {
	return Attr("profile", value...)
}

func ProgressAttr(value ...string) *AttributeNode {
	return Attr("progress", value...)
}

func ProgressbarAttr(value ...string) *AttributeNode {
	return Attr("progressbar", value...)
}

func QAttr(value ...string) *AttributeNode {
	return Attr("q", value...)
}

func QuotAttr(value ...string) *AttributeNode {
	return Attr("quot", value...)
}

func RAttr(value ...string) *AttributeNode {
	return Attr("r", value...)
}

func RadialgradientAttr(value ...string) *AttributeNode {
	return Attr("radialGradient", value...)
}

func RadioAttr(value ...string) *AttributeNode {
	return Attr("radio", value...)
}

func RadiusAttr(value ...string) *AttributeNode {
	return Attr("radius", value...)
}

func RangeAttr(value ...string) *AttributeNode {
	return Attr("range", value...)
}

func RatechangeAttr(value ...string) *AttributeNode {
	return Attr("ratechange", value...)
}

func RbAttr(value ...string) *AttributeNode {
	return Attr("rb", value...)
}

func ReadonlyAttr(value ...string) *AttributeNode {
	return Attr("readonly", value...)
}

func RectAttr(value ...string) *AttributeNode {
	return Attr("rect", value...)
}

func RefAttr(value ...string) *AttributeNode {
	return Attr("ref", value...)
}

func RefxAttr(value ...string) *AttributeNode {
	return Attr("refX", value...)
}

func RefyAttr(value ...string) *AttributeNode {
	return Attr("refY", value...)
}

func ReferrerAttr(value ...string) *AttributeNode {
	return Attr("referrer", value...)
}

func ReferrerpolicyAttr(value ...string) *AttributeNode {
	return Attr("referrerpolicy", value...)
}

func RefreshAttr(value ...string) *AttributeNode {
	return Attr("refresh", value...)
}

func RegisterprotocolhandlerAttr(value ...string) *AttributeNode {
	return Attr("registerProtocolHandler", value...)
}

func RelAttr(value ...string) *AttributeNode {
	return Attr("rel", value...)
}

func RenderAttr(value ...string) *AttributeNode {
	return Attr("render", value...)
}

func RepeatcountAttr(value ...string) *AttributeNode {
	return Attr("repeatCount", value...)
}

func RepeatdurAttr(value ...string) *AttributeNode {
	return Attr("repeatDur", value...)
}

func ReportvalidityAttr(value ...string) *AttributeNode {
	return Attr("reportValidity", value...)
}

func RequiredAttr(value ...string) *AttributeNode {
	return Attr("required", value...)
}

func RequiredfeaturesAttr(value ...string) *AttributeNode {
	return Attr("requiredFeatures", value...)
}

func ResetAttr(value ...string) *AttributeNode {
	return Attr("reset", value...)
}

func RestartAttr(value ...string) *AttributeNode {
	return Attr("restart", value...)
}

func ResultAttr(value ...string) *AttributeNode {
	return Attr("result", value...)
}

func ResultsAttr(value ...string) *AttributeNode {
	return Attr("results", value...)
}

func ReturnvalueAttr(value ...string) *AttributeNode {
	return Attr("returnValue", value...)
}

func RevAttr(value ...string) *AttributeNode {
	return Attr("rev", value...)
}

func ReversedAttr(value ...string) *AttributeNode {
	return Attr("reversed", value...)
}

func RightAttr(value ...string) *AttributeNode {
	return Attr("right", value...)
}

func RightmarginAttr(value ...string) *AttributeNode {
	return Attr("rightmargin", value...)
}

func RobotsAttr(value ...string) *AttributeNode {
	return Attr("robots", value...)
}

func RoleAttr(value ...string) *AttributeNode {
	return Attr("role", value...)
}

func RotateAttr(value ...string) *AttributeNode {
	return Attr("rotate", value...)
}

func RowAttr(value ...string) *AttributeNode {
	return Attr("row", value...)
}

func RowgroupAttr(value ...string) *AttributeNode {
	return Attr("rowgroup", value...)
}

func RowsAttr(value ...string) *AttributeNode {
	return Attr("rows", value...)
}

func RowspanAttr(value ...string) *AttributeNode {
	return Attr("rowspan", value...)
}

func RpAttr(value ...string) *AttributeNode {
	return Attr("rp", value...)
}

func RtAttr(value ...string) *AttributeNode {
	return Attr("rt", value...)
}

func RtcAttr(value ...string) *AttributeNode {
	return Attr("rtc", value...)
}

func RtlAttr(value ...string) *AttributeNode {
	return Attr("rtl", value...)
}

func RubyAttr(value ...string) *AttributeNode {
	return Attr("ruby", value...)
}

func RulesAttr(value ...string) *AttributeNode {
	return Attr("rules", value...)
}

func RxAttr(value ...string) *AttributeNode {
	return Attr("rx", value...)
}

func RyAttr(value ...string) *AttributeNode {
	return Attr("ry", value...)
}

func SAttr(value ...string) *AttributeNode {
	return Attr("s", value...)
}

func SampAttr(value ...string) *AttributeNode {
	return Attr("samp", value...)
}

func SandboxAttr(value ...string) *AttributeNode {
	return Attr("sandbox", value...)
}

func ScaleAttr(value ...string) *AttributeNode {
	return Attr("scale", value...)
}

func ScopeAttr(value ...string) *AttributeNode {
	return Attr("scope", value...)
}

func ScriptAttr(value ...string) *AttributeNode {
	return Attr("script", value...)
}

func ScriptlevelAttr(value ...string) *AttributeNode {
	return Attr("scriptlevel", value...)
}

func ScrollamountAttr(value ...string) *AttributeNode {
	return Attr("scrollamount", value...)
}

func ScrollbarAttr(value ...string) *AttributeNode {
	return Attr("scrollbar", value...)
}

func ScrolldelayAttr(value ...string) *AttributeNode {
	return Attr("scrolldelay", value...)
}

func ScrollingAttr(value ...string) *AttributeNode {
	return Attr("scrolling", value...)
}

func SearchAttr(value ...string) *AttributeNode {
	return Attr("search", value...)
}

func SearchboxAttr(value ...string) *AttributeNode {
	return Attr("searchbox", value...)
}

func SectionAttr(value ...string) *AttributeNode {
	return Attr("section", value...)
}

func SeedAttr(value ...string) *AttributeNode {
	return Attr("seed", value...)
}

func SeekedAttr(value ...string) *AttributeNode {
	return Attr("seeked", value...)
}

func SeekingAttr(value ...string) *AttributeNode {
	return Attr("seeking", value...)
}

func SelectAttr(value ...string) *AttributeNode {
	return Attr("select", value...)
}

func SelectedAttr(value ...string) *AttributeNode {
	return Attr("selected", value...)
}

func SelectedcontentAttr(value ...string) *AttributeNode {
	return Attr("selectedcontent", value...)
}

func SelfAttr(value ...string) *AttributeNode {
	return Attr("self", value...)
}

func SemanticsAttr(value ...string) *AttributeNode {
	return Attr("semantics", value...)
}

func SeparatorAttr(value ...string) *AttributeNode {
	return Attr("separator", value...)
}

func SetAttr(value ...string) *AttributeNode {
	return Attr("set", value...)
}

func SetcustomvalidityAttr(value ...string) *AttributeNode {
	return Attr("setCustomValidity", value...)
}

func SetrangetextAttr(value ...string) *AttributeNode {
	return Attr("setRangeText", value...)
}

func SetselectionrangeAttr(value ...string) *AttributeNode {
	return Attr("setSelectionRange", value...)
}

func ShadowrootclonableAttr(value ...string) *AttributeNode {
	return Attr("shadowrootclonable", value...)
}

func ShadowrootdelegatesfocusAttr(value ...string) *AttributeNode {
	return Attr("shadowrootdelegatesfocus", value...)
}

func ShadowrootmodeAttr(value ...string) *AttributeNode {
	return Attr("shadowrootmode", value...)
}

func ShadowrootserializableAttr(value ...string) *AttributeNode {
	return Attr("shadowrootserializable", value...)
}

func ShapeAttr(value ...string) *AttributeNode {
	return Attr("shape", value...)
}

func ShowAttr(value ...string) *AttributeNode {
	return Attr("show", value...)
}

func ShowmodalAttr(value ...string) *AttributeNode {
	return Attr("showModal", value...)
}

func ShowpickerAttr(value ...string) *AttributeNode {
	return Attr("showPicker", value...)
}

func SideAttr(value ...string) *AttributeNode {
	return Attr("side", value...)
}

func SizeAttr(value ...string) *AttributeNode {
	return Attr("size", value...)
}

func SizesAttr(value ...string) *AttributeNode {
	return Attr("sizes", value...)
}

func SliderAttr(value ...string) *AttributeNode {
	return Attr("slider", value...)
}

func SlopeAttr(value ...string) *AttributeNode {
	return Attr("slope", value...)
}

func SlotAttr(value ...string) *AttributeNode {
	return Attr("slot", value...)
}

func SlottedAttr(value ...string) *AttributeNode {
	return Attr("slotted", value...)
}

func SmallAttr(value ...string) *AttributeNode {
	return Attr("small", value...)
}

func SmsAttr(value ...string) *AttributeNode {
	return Attr("sms", value...)
}

func SoftAttr(value ...string) *AttributeNode {
	return Attr("soft", value...)
}

func SourceAttr(value ...string) *AttributeNode {
	return Attr("source", value...)
}

func SpacingAttr(value ...string) *AttributeNode {
	return Attr("spacing", value...)
}

func SpanAttr(value ...string) *AttributeNode {
	return Attr("span", value...)
}

func SpecularconstantAttr(value ...string) *AttributeNode {
	return Attr("specularConstant", value...)
}

func SpecularexponentAttr(value ...string) *AttributeNode {
	return Attr("specularExponent", value...)
}

func SpeculationrulesAttr(value ...string) *AttributeNode {
	return Attr("speculationrules", value...)
}

func SpellcheckAttr(value ...string) *AttributeNode {
	return Attr("spellcheck", value...)
}

func SpinbuttonAttr(value ...string) *AttributeNode {
	return Attr("spinbutton", value...)
}

func SpreadmethodAttr(value ...string) *AttributeNode {
	return Attr("spreadMethod", value...)
}

func SquareAttr(value ...string) *AttributeNode {
	return Attr("square", value...)
}

func SrcAttr(value ...string) *AttributeNode {
	return Attr("src", value...)
}

func SrcdocAttr(value ...string) *AttributeNode {
	return Attr("srcdoc", value...)
}

func SrclangAttr(value ...string) *AttributeNode {
	return Attr("srclang", value...)
}

func SrcsetAttr(value ...string) *AttributeNode {
	return Attr("srcset", value...)
}

func StalledAttr(value ...string) *AttributeNode {
	return Attr("stalled", value...)
}

func StandbyAttr(value ...string) *AttributeNode {
	return Attr("standby", value...)
}

func StartAttr(value ...string) *AttributeNode {
	return Attr("start", value...)
}

func StartoffsetAttr(value ...string) *AttributeNode {
	return Attr("startOffset", value...)
}

func StddeviationAttr(value ...string) *AttributeNode {
	return Attr("stdDeviation", value...)
}

func StepAttr(value ...string) *AttributeNode {
	return Attr("step", value...)
}

func StepdownAttr(value ...string) *AttributeNode {
	return Attr("stepDown", value...)
}

func StepupAttr(value ...string) *AttributeNode {
	return Attr("stepUp", value...)
}

func StitchtilesAttr(value ...string) *AttributeNode {
	return Attr("stitchTiles", value...)
}

func StopAttr(value ...string) *AttributeNode {
	return Attr("stop", value...)
}

func StrikeAttr(value ...string) *AttributeNode {
	return Attr("strike", value...)
}

func StrokeAttr(value ...string) *AttributeNode {
	return Attr("stroke", value...)
}

func StrongAttr(value ...string) *AttributeNode {
	return Attr("strong", value...)
}

func StyleAttr(value ...string) *AttributeNode {
	return Attr("style", value...)
}

func StylesheetAttr(value ...string) *AttributeNode {
	return Attr("stylesheet", value...)
}

func SubAttr(value ...string) *AttributeNode {
	return Attr("sub", value...)
}

func SubmitAttr(value ...string) *AttributeNode {
	return Attr("submit", value...)
}

func SubtitlesAttr(value ...string) *AttributeNode {
	return Attr("subtitles", value...)
}

func SummaryAttr(value ...string) *AttributeNode {
	return Attr("summary", value...)
}

func SupAttr(value ...string) *AttributeNode {
	return Attr("sup", value...)
}

func SurfacescaleAttr(value ...string) *AttributeNode {
	return Attr("surfaceScale", value...)
}

func SuspendAttr(value ...string) *AttributeNode {
	return Attr("suspend", value...)
}

func SvgAttr(value ...string) *AttributeNode {
	return Attr("svg", value...)
}

func SwitchAttr(value ...string) *AttributeNode {
	return Attr("switch", value...)
}

func SymbolAttr(value ...string) *AttributeNode {
	return Attr("symbol", value...)
}

func SyncAttr(value ...string) *AttributeNode {
	return Attr("sync", value...)
}

func SystemlanguageAttr(value ...string) *AttributeNode {
	return Attr("systemLanguage", value...)
}

func TabAttr(value ...string) *AttributeNode {
	return Attr("tab", value...)
}

func TabindexAttr(value ...string) *AttributeNode {
	return Attr("tabindex", value...)
}

func TableAttr(value ...string) *AttributeNode {
	return Attr("table", value...)
}

func TablevaluesAttr(value ...string) *AttributeNode {
	return Attr("tableValues", value...)
}

func TargetAttr(value ...string) *AttributeNode {
	return Attr("target", value...)
}

func TargetxAttr(value ...string) *AttributeNode {
	return Attr("targetX", value...)
}

func TargetyAttr(value ...string) *AttributeNode {
	return Attr("targetY", value...)
}

func TbodyAttr(value ...string) *AttributeNode {
	return Attr("tbody", value...)
}

func TdAttr(value ...string) *AttributeNode {
	return Attr("td", value...)
}

func TelAttr(value ...string) *AttributeNode {
	return Attr("tel", value...)
}

func TemplateAttr(value ...string) *AttributeNode {
	return Attr("template", value...)
}

func TextAttr(value ...string) *AttributeNode {
	return Attr("text", value...)
}

func TextlengthAttr(value ...string) *AttributeNode {
	return Attr("textLength", value...)
}

func TextpathAttr(value ...string) *AttributeNode {
	return Attr("textPath", value...)
}

func TextareaAttr(value ...string) *AttributeNode {
	return Attr("textarea", value...)
}

func TextboxAttr(value ...string) *AttributeNode {
	return Attr("textbox", value...)
}

func TfootAttr(value ...string) *AttributeNode {
	return Attr("tfoot", value...)
}

func ThAttr(value ...string) *AttributeNode {
	return Attr("th", value...)
}

func TheadAttr(value ...string) *AttributeNode {
	return Attr("thead", value...)
}

func TimeAttr(value ...string) *AttributeNode {
	return Attr("time", value...)
}

func TimeupdateAttr(value ...string) *AttributeNode {
	return Attr("timeupdate", value...)
}

func TitleAttr(value ...string) *AttributeNode {
	return Attr("title", value...)
}

func ToAttr(value ...string) *AttributeNode {
	return Attr("to", value...)
}

func ToggleAttr(value ...string) *AttributeNode {
	return Attr("toggle", value...)
}

func TopAttr(value ...string) *AttributeNode {
	return Attr("top", value...)
}

func TopmarginAttr(value ...string) *AttributeNode {
	return Attr("topmargin", value...)
}

func TrAttr(value ...string) *AttributeNode {
	return Attr("tr", value...)
}

func TrackAttr(value ...string) *AttributeNode {
	return Attr("track", value...)
}

func TransformAttr(value ...string) *AttributeNode {
	return Attr("transform", value...)
}

func TranslateAttr(value ...string) *AttributeNode {
	return Attr("translate", value...)
}

func TreeitemAttr(value ...string) *AttributeNode {
	return Attr("treeitem", value...)
}

func TrueAttr(value ...string) *AttributeNode {
	return Attr("true", value...)
}

func TruespeedAttr(value ...string) *AttributeNode {
	return Attr("truespeed", value...)
}

func TspanAttr(value ...string) *AttributeNode {
	return Attr("tspan", value...)
}

func TtAttr(value ...string) *AttributeNode {
	return Attr("tt", value...)
}

func TypeAttr(value ...string) *AttributeNode {
	return Attr("type", value...)
}

func UAttr(value ...string) *AttributeNode {
	return Attr("u", value...)
}

func UlAttr(value ...string) *AttributeNode {
	return Attr("ul", value...)
}

func UnfencedtopAttr(value ...string) *AttributeNode {
	return Attr("unfencedTop", value...)
}

func UrlAttr(value ...string) *AttributeNode {
	return Attr("url", value...)
}

func UseAttr(value ...string) *AttributeNode {
	return Attr("use", value...)
}

func UsemapAttr(value ...string) *AttributeNode {
	return Attr("usemap", value...)
}

func VAttr(value ...string) *AttributeNode {
	return Attr("v", value...)
}

func ValidAttr(value ...string) *AttributeNode {
	return Attr("valid", value...)
}

func ValignAttr(value ...string) *AttributeNode {
	return Attr("valign", value...)
}

func ValueAttr(value ...string) *AttributeNode {
	return Attr("value", value...)
}

func ValuesAttr(value ...string) *AttributeNode {
	return Attr("values", value...)
}

func ValuetypeAttr(value ...string) *AttributeNode {
	return Attr("valuetype", value...)
}

func VarAttr(value ...string) *AttributeNode {
	return Attr("var", value...)
}

func VersionAttr(value ...string) *AttributeNode {
	return Attr("version", value...)
}

func VideoAttr(value ...string) *AttributeNode {
	return Attr("video", value...)
}

func ViewAttr(value ...string) *AttributeNode {
	return Attr("view", value...)
}

func ViewboxAttr(value ...string) *AttributeNode {
	return Attr("viewBox", value...)
}

func ViewportAttr(value ...string) *AttributeNode {
	return Attr("viewport", value...)
}

func VirtualkeyboardpolicyAttr(value ...string) *AttributeNode {
	return Attr("virtualkeyboardpolicy", value...)
}

func VisibilityAttr(value ...string) *AttributeNode {
	return Attr("visibility", value...)
}

func VisitedAttr(value ...string) *AttributeNode {
	return Attr("visited", value...)
}

func VlinkAttr(value ...string) *AttributeNode {
	return Attr("vlink", value...)
}

func VolumechangeAttr(value ...string) *AttributeNode {
	return Attr("volumechange", value...)
}

func VspaceAttr(value ...string) *AttributeNode {
	return Attr("vspace", value...)
}

func WAttr(value ...string) *AttributeNode {
	return Attr("w", value...)
}

func WaitingAttr(value ...string) *AttributeNode {
	return Attr("waiting", value...)
}

func WbrAttr(value ...string) *AttributeNode {
	return Attr("wbr", value...)
}

func WebkitdirectoryAttr(value ...string) *AttributeNode {
	return Attr("webkitdirectory", value...)
}

func WeekAttr(value ...string) *AttributeNode {
	return Attr("week", value...)
}

func WidthAttr(value ...string) *AttributeNode {
	return Attr("width", value...)
}

func WorkerAttr(value ...string) *AttributeNode {
	return Attr("worker", value...)
}

func WrapAttr(value ...string) *AttributeNode {
	return Attr("wrap", value...)
}

func WritingsuggestionsAttr(value ...string) *AttributeNode {
	return Attr("writingsuggestions", value...)
}

func XAttr(value ...string) *AttributeNode {
	return Attr("x", value...)
}

func X1Attr(value ...string) *AttributeNode {
	return Attr("x1", value...)
}

func X2Attr(value ...string) *AttributeNode {
	return Attr("x2", value...)
}

func XchannelselectorAttr(value ...string) *AttributeNode {
	return Attr("xChannelSelector", value...)
}

func XmlnsAttr(value ...string) *AttributeNode {
	return Attr("xmlns", value...)
}

func XmpAttr(value ...string) *AttributeNode {
	return Attr("xmp", value...)
}

func YAttr(value ...string) *AttributeNode {
	return Attr("y", value...)
}

func Y1Attr(value ...string) *AttributeNode {
	return Attr("y1", value...)
}

func Y2Attr(value ...string) *AttributeNode {
	return Attr("y2", value...)
}

func YchannelselectorAttr(value ...string) *AttributeNode {
	return Attr("yChannelSelector", value...)
}

func YesAttr(value ...string) *AttributeNode {
	return Attr("yes", value...)
}

func ZAttr(value ...string) *AttributeNode {
	return Attr("z", value...)
}

func ZoomandpanAttr(value ...string) *AttributeNode {
	return Attr("zoomAndPan", value...)
}

// Data Attributes

/*
Data attribute helper for creating custom data-* attributes
*/
func DataAttr(name string, value ...string) *AttributeNode {
	return Attr("data-"+name, value...)
}
